# Settings for the app
app:
  # HTML Title
  title: Divvy Suggestion Map
  # Header name
  name: Divvy Suggestion Map
  # Meta description that will show up in Google search results
  meta_description: _(Divvy Suggestion Map. Where do you want bike share stations?)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  geocoding_enabled: true
  options:
    center:
      lat: 41.8819
      lng: -87.6278
    zoom: 14
    minZoom: 10
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  new-suggestion:
    label: _(new station)
    rules:
      - condition: '"{{location_type}}" === "new-suggestion"'

        icon:
          iconUrl: /static/css/images/marker-comment-new.png
          iconSize: [21, 22]
          iconAnchor: [17, 18]
        focus_icon:
          iconUrl: /static/css/images/marker-comment-focused.png
          iconSize: [21, 22]
          iconAnchor: [17, 18]

  existing-station:
    label: _(existing station)
    rules:
      - condition: '"{{location_type}}" === "existing-station"'
        icon:
          iconUrl: /static/css/images/marker-station-existing.png
          iconSize: [40, 53]
          iconAnchor: [21, 49]
        focus_icon:
          iconUrl: /static/css/images/marker-station-focused.png
          iconSize: [40, 53]
          iconAnchor: [21, 49]

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Suggest a Location)
  action_text: _(suggested)
  title: _(Tell us more...)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - type: hidden
      name: location_type
      attrs:
        - key: value
          value: new-suggestion

    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30

    - prompt: _(Your Email)
      type: text
      name: private-email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email)
        - key: size
          value: 30

    - prompt: _(Description)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Description...)
        - key: required

    - prompt: _(Work/School)
      type: checkbox
      name: work
      attrs:
        - key: value
          value: _(Work/School)

    - prompt: _(Shopping)
      type: checkbox
      name: shopping
      attrs:
        - key: value
          value: _(Shopping)

    - prompt: _(Fun)
      type: checkbox
      name: fun
      attrs:
        - key: value
          value: _(Fun)

    - prompt: _(Home)
      type: checkbox
      name: home
      attrs:
        - key: value
          value: _(Home)

    - prompt: _(Home Zip Code)
      type: text
      name: zip
      optional: true
      attrs:
        - key: placeholder
          value: _(Zip Code)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: placeholder
          value: _(Your comment...)
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: _(Go to divvybikes.com)
    external: true
    url: https://divvybikes.com/
